

// Do not edit directly
// Generated on Fri, 05 Apr 2024 11:47:41 GMT



package fushion.fundamentals.token;

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.*

object FushionLightColor {
  val colorLightNewsBackground = Color(0xfffafdfd)
  val colorLightNewsError = Color(0xffba1a1a)
  val colorLightNewsErrorContainer = Color(0xffffdad6)
  val colorLightNewsInverseOnSurface = Color(0xffeff1f1)
  val colorLightNewsInversePrimary = Color(0xff4fd8eb)
  val colorLightNewsInverseSurface = Color(0xff2e3132)
  val colorLightNewsOnBackground = Color(0xff191c1d)
  val colorLightNewsOnError = Color(0xffffffff)
  val colorLightNewsOnErrorContainer = Color(0xff410002)
  val colorLightNewsOnPrimary = Color(0xffffffff)
  val colorLightNewsOnPrimaryContainer = Color(0xff001f24)
  val colorLightNewsOnSecondary = Color(0xffffffff)
  val colorLightNewsOnSecondaryContainer = Color(0xff051f23)
  val colorLightNewsOnSurface = Color(0xff191c1d)
  val colorLightNewsOnSurfaceVariant = Color(0xff3f484a)
  val colorLightNewsOnTertiary = Color(0xffffffff)
  val colorLightNewsOnTertiaryContainer = Color(0xff0e1b37)
  val colorLightNewsOutline = Color(0xff6f797a)
  val colorLightNewsOutlineVariant = Color(0xffbfc8ca)
  val colorLightNewsPrimary = Color(0xff006874)
  val colorLightNewsPrimaryContainer = Color(0xff97f0ff)
  val colorLightNewsScrim = Color(0xff000000)
  val colorLightNewsSecondary = Color(0xff4a6267)
  val colorLightNewsSecondaryContainer = Color(0xffcde7ec)
  val colorLightNewsShadow = Color(0xff000000)
  val colorLightNewsSurface = Color(0xfffafdfd)
  val colorLightNewsSurfaceTint = Color(0xff006874)
  val colorLightNewsSurfaceVariant = Color(0xffdbe4e6)
  val colorLightNewsTertiary = Color(0xff525e7d)
  val colorLightNewsTertiaryContainer = Color(0xffdae2ff)
  val colorLightOlympicBackground = Color(0xfffffbff)
  val colorLightOlympicError = Color(0xffba1a1a)
  val colorLightOlympicErrorContainer = Color(0xffffdad6)
  val colorLightOlympicInverseOnSurface = Color(0xfff5eff4)
  val colorLightOlympicInversePrimary = Color(0xffdbb8ff)
  val colorLightOlympicInverseSurface = Color(0xff322f33)
  val colorLightOlympicOnBackground = Color(0xff1d1b1e)
  val colorLightOlympicOnError = Color(0xffffffff)
  val colorLightOlympicOnErrorContainer = Color(0xff410002)
  val colorLightOlympicOnPrimary = Color(0xffffffff)
  val colorLightOlympicOnPrimaryContainer = Color(0xff2b0052)
  val colorLightOlympicOnSecondary = Color(0xffffffff)
  val colorLightOlympicOnSecondaryContainer = Color(0xff20182a)
  val colorLightOlympicOnSurface = Color(0xff1d1b1e)
  val colorLightOlympicOnSurfaceVariant = Color(0xff4a454e)
  val colorLightOlympicOnTertiary = Color(0xffffffff)
  val colorLightOlympicOnTertiaryContainer = Color(0xff321017)
  val colorLightOlympicOutline = Color(0xff7b757f)
  val colorLightOlympicOutlineVariant = Color(0xffccc4cf)
  val colorLightOlympicPrimary = Color(0xff7d39c5)
  val colorLightOlympicPrimaryContainer = Color(0xffefdbff)
  val colorLightOlympicScrim = Color(0xff000000)
  val colorLightOlympicSecondary = Color(0xff655a6f)
  val colorLightOlympicSecondaryContainer = Color(0xffecddf6)
  val colorLightOlympicShadow = Color(0xff000000)
  val colorLightOlympicSurface = Color(0xfffffbff)
  val colorLightOlympicSurfaceTint = Color(0xff7d39c5)
  val colorLightOlympicSurfaceVariant = Color(0xffe9e0eb)
  val colorLightOlympicTertiary = Color(0xff805159)
  val colorLightOlympicTertiaryContainer = Color(0xffffd9dd)
  val colorLightSoccerBackground = Color(0xfffffbff)
  val colorLightSoccerError = Color(0xffba1a1a)
  val colorLightSoccerErrorContainer = Color(0xffffdad6)
  val colorLightSoccerInverseOnSurface = Color(0xfffbeeec)
  val colorLightSoccerInversePrimary = Color(0xffffb4aa)
  val colorLightSoccerInverseSurface = Color(0xff362f2e)
  val colorLightSoccerOnBackground = Color(0xff201a19)
  val colorLightSoccerOnError = Color(0xffffffff)
  val colorLightSoccerOnErrorContainer = Color(0xff410002)
  val colorLightSoccerOnPrimary = Color(0xffffffff)
  val colorLightSoccerOnPrimaryContainer = Color(0xff410001)
  val colorLightSoccerOnSecondary = Color(0xffffffff)
  val colorLightSoccerOnSecondaryContainer = Color(0xff2c1512)
  val colorLightSoccerOnSurface = Color(0xff201a19)
  val colorLightSoccerOnSurfaceVariant = Color(0xff534341)
  val colorLightSoccerOnTertiary = Color(0xffffffff)
  val colorLightSoccerOnTertiaryContainer = Color(0xff261a00)
  val colorLightSoccerOutline = Color(0xff857370)
  val colorLightSoccerOutlineVariant = Color(0xffd8c2be)
  val colorLightSoccerPrimary = Color(0xffc0000a)
  val colorLightSoccerPrimaryContainer = Color(0xffffdad5)
  val colorLightSoccerScrim = Color(0xff000000)
  val colorLightSoccerSecondary = Color(0xff775652)
  val colorLightSoccerSecondaryContainer = Color(0xffffdad5)
  val colorLightSoccerShadow = Color(0xff000000)
  val colorLightSoccerSurface = Color(0xfffffbff)
  val colorLightSoccerSurfaceTint = Color(0xffc0000a)
  val colorLightSoccerSurfaceVariant = Color(0xfff5ddda)
  val colorLightSoccerTertiary = Color(0xff705c2e)
  val colorLightSoccerTertiaryContainer = Color(0xfffcdfa6)
}
