

// Do not edit directly
// Generated on Fri, 05 Apr 2024 11:47:41 GMT



package fushion.fundamentals.token;

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.*

object FushionDarkColor {
  val colorDarkNewsBackground = Color(0xff191c1d)
  val colorDarkNewsError = Color(0xffffb4ab)
  val colorDarkNewsErrorContainer = Color(0xff93000a)
  val colorDarkNewsInverseOnSurface = Color(0xff191c1d)
  val colorDarkNewsInversePrimary = Color(0xff006874)
  val colorDarkNewsInverseSurface = Color(0xffe1e3e3)
  val colorDarkNewsOnBackground = Color(0xffe1e3e3)
  val colorDarkNewsOnError = Color(0xff690005)
  val colorDarkNewsOnErrorContainer = Color(0xffffdad6)
  val colorDarkNewsOnPrimary = Color(0xff00363d)
  val colorDarkNewsOnPrimaryContainer = Color(0xff97f0ff)
  val colorDarkNewsOnSecondary = Color(0xff1c3438)
  val colorDarkNewsOnSecondaryContainer = Color(0xffcde7ec)
  val colorDarkNewsOnSurface = Color(0xffe1e3e3)
  val colorDarkNewsOnSurfaceVariant = Color(0xffbfc8ca)
  val colorDarkNewsOnTertiary = Color(0xff24304d)
  val colorDarkNewsOnTertiaryContainer = Color(0xffdae2ff)
  val colorDarkNewsOutline = Color(0xff899294)
  val colorDarkNewsOutlineVariant = Color(0xff3f484a)
  val colorDarkNewsPrimary = Color(0xff4fd8eb)
  val colorDarkNewsPrimaryContainer = Color(0xff004f58)
  val colorDarkNewsScrim = Color(0xff000000)
  val colorDarkNewsSecondary = Color(0xffb1cbd0)
  val colorDarkNewsSecondaryContainer = Color(0xff334b4f)
  val colorDarkNewsShadow = Color(0xff000000)
  val colorDarkNewsSurface = Color(0xff191c1d)
  val colorDarkNewsSurfaceTint = Color(0xff4fd8eb)
  val colorDarkNewsSurfaceVariant = Color(0xff3f484a)
  val colorDarkNewsTertiary = Color(0xffbac6ea)
  val colorDarkNewsTertiaryContainer = Color(0xff3b4664)
  val colorDarkOlympicBackground = Color(0xff1d1b1e)
  val colorDarkOlympicError = Color(0xffffb4ab)
  val colorDarkOlympicErrorContainer = Color(0xff93000a)
  val colorDarkOlympicInverseOnSurface = Color(0xff1d1b1e)
  val colorDarkOlympicInversePrimary = Color(0xff7d39c5)
  val colorDarkOlympicInverseSurface = Color(0xffe7e1e5)
  val colorDarkOlympicOnBackground = Color(0xffe7e1e5)
  val colorDarkOlympicOnError = Color(0xff690005)
  val colorDarkOlympicOnErrorContainer = Color(0xffffdad6)
  val colorDarkOlympicOnPrimary = Color(0xff480083)
  val colorDarkOlympicOnPrimaryContainer = Color(0xffefdbff)
  val colorDarkOlympicOnSecondary = Color(0xff362d3f)
  val colorDarkOlympicOnSecondaryContainer = Color(0xffecddf6)
  val colorDarkOlympicOnSurface = Color(0xffe7e1e5)
  val colorDarkOlympicOnSurfaceVariant = Color(0xffccc4cf)
  val colorDarkOlympicOnTertiary = Color(0xff4b252c)
  val colorDarkOlympicOnTertiaryContainer = Color(0xffffd9dd)
  val colorDarkOlympicOutline = Color(0xff958e98)
  val colorDarkOlympicOutlineVariant = Color(0xff4a454e)
  val colorDarkOlympicPrimary = Color(0xffdbb8ff)
  val colorDarkOlympicPrimaryContainer = Color(0xff6417ab)
  val colorDarkOlympicScrim = Color(0xff000000)
  val colorDarkOlympicSecondary = Color(0xffd0c1da)
  val colorDarkOlympicSecondaryContainer = Color(0xff4d4357)
  val colorDarkOlympicShadow = Color(0xff000000)
  val colorDarkOlympicSurface = Color(0xff1d1b1e)
  val colorDarkOlympicSurfaceTint = Color(0xffdbb8ff)
  val colorDarkOlympicSurfaceVariant = Color(0xff4a454e)
  val colorDarkOlympicTertiary = Color(0xfff3b7bf)
  val colorDarkOlympicTertiaryContainer = Color(0xff653b41)
  val colorDarkSoccerBackground = Color(0xff201a19)
  val colorDarkSoccerError = Color(0xffffb4ab)
  val colorDarkSoccerErrorContainer = Color(0xff93000a)
  val colorDarkSoccerInverseOnSurface = Color(0xff201a19)
  val colorDarkSoccerInversePrimary = Color(0xffc0000a)
  val colorDarkSoccerInverseSurface = Color(0xffede0de)
  val colorDarkSoccerOnBackground = Color(0xffede0de)
  val colorDarkSoccerOnError = Color(0xff690005)
  val colorDarkSoccerOnErrorContainer = Color(0xffffdad6)
  val colorDarkSoccerOnPrimary = Color(0xff690003)
  val colorDarkSoccerOnPrimaryContainer = Color(0xffffdad5)
  val colorDarkSoccerOnSecondary = Color(0xff442926)
  val colorDarkSoccerOnSecondaryContainer = Color(0xffffdad5)
  val colorDarkSoccerOnSurface = Color(0xffede0de)
  val colorDarkSoccerOnSurfaceVariant = Color(0xffd8c2be)
  val colorDarkSoccerOnTertiary = Color(0xff3e2e04)
  val colorDarkSoccerOnTertiaryContainer = Color(0xfffcdfa6)
  val colorDarkSoccerOutline = Color(0xffa08c8a)
  val colorDarkSoccerOutlineVariant = Color(0xff534341)
  val colorDarkSoccerPrimary = Color(0xffffb4aa)
  val colorDarkSoccerPrimaryContainer = Color(0xff930006)
  val colorDarkSoccerScrim = Color(0xff000000)
  val colorDarkSoccerSecondary = Color(0xffe7bdb7)
  val colorDarkSoccerSecondaryContainer = Color(0xff5d3f3b)
  val colorDarkSoccerShadow = Color(0xff000000)
  val colorDarkSoccerSurface = Color(0xff201a19)
  val colorDarkSoccerSurfaceTint = Color(0xffffb4aa)
  val colorDarkSoccerSurfaceVariant = Color(0xff534341)
  val colorDarkSoccerTertiary = Color(0xffdfc38c)
  val colorDarkSoccerTertiaryContainer = Color(0xff574419)
}
